import React, { useState } from 'react';
import { useChat } from '../context/ChatContext';
import { X, Download, Copy, Check, FileCode, FileText, Database } from 'lucide-react';

export default function ExportModal() {
  const { isExportOpen, setIsExportOpen, currentChat } = useChat();
  const [format, setFormat] = useState('markdown');
  const [copied, setCopied] = useState(false);

  if (!isExportOpen) return null;

  const messages = currentChat?.messages || [];

  function generateExportContent() {
    if (format === 'json') {
      return JSON.stringify(currentChat, null, 2);
    }

    if (format === 'markdown') {
      let md = `# ${currentChat?.title || 'NamoGPT Conversation'}\n\n`;
      md += `*Generated by NamoGPT on ${new Date().toLocaleString()}*\n\n---\n\n`;
      messages.forEach((m) => {
        const sender = m.role === 'user' ? '### 👤 User' : `### ✨ NamoGPT (${m.modelUsed || 'AI'})`;
        md += `${sender}\n\n${m.content}\n\n---\n\n`;
      });
      return md;
    }

    // Plain text
    let txt = `=== ${currentChat?.title || 'NamoGPT Conversation'} ===\n\n`;
    messages.forEach((m) => {
      const sender = m.role === 'user' ? 'USER:' : 'NAMOGPT:';
      txt += `${sender}\n${m.content}\n\n----------------------------------------\n\n`;
    });
    return txt;
  }

  const exportText = generateExportContent();

  function handleCopy() {
    navigator.clipboard.writeText(exportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleDownload() {
    const ext = format === 'markdown' ? 'md' : format === 'json' ? 'json' : 'txt';
    const mime = format === 'json' ? 'application/json' : 'text/plain';
    const blob = new Blob([exportText], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NamoGPT-${(currentChat?.title || 'Chat').replace(/[^a-zA-Z0-9]/g, '_')}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm select-none">
      <div className="bg-[#171717] border border-[#303030] rounded-2xl w-full max-w-lg shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#303030]">
          <h2 className="text-base font-semibold text-white">Export Conversation</h2>
          <button
            onClick={() => setIsExportOpen(false)}
            className="p-1 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <div className="grid grid-cols-3 gap-2.5">
            <button
              onClick={() => setFormat('markdown')}
              className={`p-3 rounded-xl border flex flex-col items-center gap-1.5 transition-all ${
                format === 'markdown'
                  ? 'border-emerald-500 bg-emerald-500/10 text-white font-medium'
                  : 'border-zinc-800 bg-[#212121] text-zinc-400 hover:text-white'
              }`}
            >
              <FileCode className="w-5 h-5 text-emerald-400" />
              <span className="text-xs">Markdown</span>
            </button>
            <button
              onClick={() => setFormat('json')}
              className={`p-3 rounded-xl border flex flex-col items-center gap-1.5 transition-all ${
                format === 'json'
                  ? 'border-emerald-500 bg-emerald-500/10 text-white font-medium'
                  : 'border-zinc-800 bg-[#212121] text-zinc-400 hover:text-white'
              }`}
            >
              <Database className="w-5 h-5 text-blue-400" />
              <span className="text-xs">JSON</span>
            </button>
            <button
              onClick={() => setFormat('text')}
              className={`p-3 rounded-xl border flex flex-col items-center gap-1.5 transition-all ${
                format === 'text'
                  ? 'border-emerald-500 bg-emerald-500/10 text-white font-medium'
                  : 'border-zinc-800 bg-[#212121] text-zinc-400 hover:text-white'
              }`}
            >
              <FileText className="w-5 h-5 text-amber-400" />
              <span className="text-xs">Plain Text</span>
            </button>
          </div>

          <div className="relative">
            <pre className="p-3 bg-zinc-900 border border-zinc-800 rounded-xl text-xs font-mono text-zinc-300 max-h-48 overflow-y-auto whitespace-pre-wrap">
              {exportText}
            </pre>
          </div>
        </div>

        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-[#303030] bg-[#141414]">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 px-4 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-white text-xs font-medium border border-zinc-700 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center space-x-1.5 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow-md transition-all hover:scale-[1.02]"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download File</span>
          </button>
        </div>
      </div>
    </div>
  );
}
